# Change these first
owner: delirehberi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Emre.xyz
    url: https://emre.xyz
  - name: Bilimma
    url: https://bilimma.com
  - name: Eres
    url: https://www.eresbiotech.com
  - name: Tarihi Sanat
    url: https://tarihisanat.com
  - name: Ekog
    url: https://ekog.org
  - name: Webend
    url: https://webend.org 
  - name: Hedef
    url: https://hedef.im
  - name: acikbelediye
    url: https://acikbelediye.com
  - name: Workouse
    url: https://workouse.com
  - name: Electrouse
    url: https://electrouse.com
  - name: Elcin Eksi
    url: https://elcineksi.com
  - name: Arkeozooloji
    url: https://arkeozooloji.com
  - name: Ankaranin Dogasi
    url: https://ankaranindogasi.com
  - name: History of art
    url: https://historyofart.emre.xyz
  - name: Aydin Yazilimci Agi
    url: https://aya.emre.xyz
  - name: Certifly
    url: https://getcertifly.com
  - name: Bioinformy
    url: https://bioinformy.com
  - name: Bilim Kadinlari
    url: https://bilimkadinlari.com
  - name: Adu STT
    url: https://adustt.com
  - name: Ses Seda
    url: https://sesseda.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.emre.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://pbs.twimg.com/profile_images/1442868043965612033/5m2ytVRa_400x400.jpg
  name: Delirehberi
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime info of my sites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://emre.xyz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
